### PR TITLE
Setup react app dev environment

### PR DESCRIPTION
**Pull request by alexiscyber14**
Requirements:
Make sure that there are [no linter errors](https://github.com/microverseinc/linters-config). Remember that this is your first React project and it requires a special linters setup. Check the instructions in the linters-config README.
Make sure that you used correct [Gitflow](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/gitflow.md).

### CODE REVIEW

**Comment by prolajumokeoni** [comment]
Hi @alexiscyber14  

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not follow proper [Gitflow](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/gitflow.md)

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by alexiscyber14** [comment]
@prolajumokeoni  the project is about setting up the react development environment. i haven't created any other branches apart from main en dev

**Comment by alexiscyber14** [comment]
@prolajumokeoni  Hello

**Comment by prolajumokeoni** [comment]
Hi @alexiscyber14, For your setup you still need to follow proper [Gitflow](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/gitflow.md), please create another branch setup  and also setup linters and add a readme using  the updated Microverse readme template 👍🏿

**Pull request closed without merging**
